some minor fixes
francescobrivio/KLUBAnalysis pull request #11
Opened 2020-04-30 09:59 UTC by camendola

See: 
* https://github.com/camendola/KLUBAnalysis/pull/34/files#r417876569
* https://github.com/camendola/KLUBAnalysis/pull/34/files#r417502313

And some indentation fixes

2020-04-30 10:00 UTC, camendola commented
@francescobrivio let's leave it open for a bit in case some other change turns out to be necessary

2020-05-01 09:59 UTC, francescobrivio requested changes

2020-05-01 09:59 UTC, francescobrivio commented on test/skimNtuple2018.cpp
> +    Year DNN_e_year(y17);
this should be `y18`

2020-05-01 14:16 UTC, camendola commented
@francescobrivio Closing this PR and making another one from scratch to resolve conflicts

2020-05-01 14:16 UTC, closed without merging