First modifications for 2018
francescobrivio/KLUBAnalysis pull request #3
Opened 2019-06-06 09:41 UTC by dzuolo

Added branches in bigTree, skimNtuple.cpp and smallTree to store the new deepTauID scores for dau1 and dau2 and the deepFlavor scores for all the used jets.
Created a new skimNtuple config file for 2018. At the moment is a copy of the 2017 one with a new flag ("useDeepFlavor = false") to use deepFlavor score to order bjets.
Added deepFlavor SF csv file for 2018.
Added deepCSV and deepFlavor WPSet to bTagSF.cc
See https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePFTauID#Running_of_the_DeepTauIDs_ver_20 for the new DNN based TauID.
See https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation102X for bTagging related changes.

2019-06-14 15:26 UTC, dzuolo commented
Added first IdIso and Trigger SF files from https://github.com/CMS-HTT/LeptonEfficiencies (Electron and Muon Trigger And IdIso SF files) and https://github.com/cms-tau-pog/TauTriggerSFs (Tau Trigger SF Files). Tau ID SF are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/TauIDRecommendation13TeV#Tau_ID_efficiency

2019-06-17 15:51 UTC, dzuolo commented
Added txt file, data PU distribution and instructions in the code for 2018 data sample PUReweight.
Fixed some bugs discovered after trying to submit skim jobs.

2019-06-18 15:43 UTC, dzuolo commented
DeepTau branches temporary commented: check if the output is floating or integer and eventually fix in LLR

2019-07-05 09:51 UTC, francescobrivio requested changes

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +  	bTagSFHelper.SetWPset("102X_DeepFlavor_V1"); // third field unused, but could be needed to select efficiencies for different selection levels
the "bTag_SFFile" and "bTag_effFile" are read directly from the cfg right?
maybe it's bettere to have different files for deepCSV and deepFlavor also in the config, so we do not have to change them every time, you can just change the "useDeepFlavor" flag and the rest is all automatic

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +        if (jets_and_sortPar.at(njets-2).first>0.4184) bPairFound = true; // medium WP is: 0.8484 for 2016 CSV, 0.4941 for 2017 DeepCSV, 0.4184 for 2018 DeepCSV,  0.2770 for 2018 DeepFlavor
shouldn't this be like the other deepCSV/deepFlavor choice? 
something like:
```
if(useDeepFlavor)
   if (jets_and_sortPar.at(njets-2).first>0.2770) bPairFound = true;  
else
   if (jets_and_sortPar.at(njets-2).first>0.4184) bPairFound = true;
```

2019-07-05 09:51 UTC, francescobrivio commented on config/skim_2018_sync_mib.cfg
> +### skimNtuple.exe filelist_sync13Sett.txt output_HH_sync_14Set.root 10.0 0  config/skim_2016_sync.cfg  0  1.0 -999.0 0  0  0 0 1
lines 1 and 2 can be deleted I think...

2019-07-05 09:51 UTC, francescobrivio commented on config/skim_2018_sync_mib.cfg
> +SFFile  = /gwpool/users/dzuolo/HbbtautauAnalysis2018/CMSSW_9_0_0/src/KLUBAnalysis/weights/DeepCSV_102XSF_V1.csv
we should create 2 different SFFiles and in skimNtuple read one or the other based on the "useDeepFlavor" flag:
```
SFFile_deepCSV
SFFfile_deepFlavor
```

2019-07-05 09:51 UTC, francescobrivio commented on config/skim_2018_sync_mib.cfg
> +effFile  = /gwpool/users/dzuolo/HbbtautauAnalysis2018/CMSSW_9_0_0/src/KLUBAnalysis/weights/bTagEfficiencies_94X_2018WPs_Fall17MC_cleanJets.root
same comment as line 187

2019-07-05 09:51 UTC, francescobrivio commented on interface/PUReweight.h
> +  std::vector<float> hT2018_MCAutumun18_Data59c7fb; // Full Run2018
Autumun --> Autumn

2019-07-05 09:51 UTC, francescobrivio commented on interface/PUReweight.h
> +  std::vector<float> hT2018_MCAutumun18_Data59c7fb_special;  // Full Run2018 - weights read from external txt file
Autumun --> Autumn

2019-07-05 09:51 UTC, francescobrivio commented on interface/smallTree.h
> +
delete a couple of these empty lines

2019-07-05 09:51 UTC, francescobrivio commented on src/PUReweight.cc
> +      return hT2018_MCAutumun18_Data59c7fb.at(input) ;         // Full 2018
Autumun --> Autumn

2019-07-05 09:51 UTC, francescobrivio commented on src/PUReweight.cc
> +        return hT2018_MCAutumun18_Data59c7fb_special.at(input) ;
Autumun --> Autumn

2019-07-05 09:51 UTC, francescobrivio commented on src/PUReweight.cc
> +  	hT2018_MCAutumun18_Data59c7fb.push_back(npuAutumn18_59c7fb[k]) ;
Autumun --> Autumn

2019-07-05 09:51 UTC, francescobrivio commented on src/PUReweight.cc
> +        hT2018_MCAutumun18_Data59c7fb_special.push_back(0.0) ; // if no filename passe, initialize a vector of 0s
Autumun --> Autumn

2019-07-05 09:51 UTC, francescobrivio commented on src/PUReweight.cc
> +    hT2018_MCAutumun18_Data59c7fb_special = LoadExternalWeights(theFilename);
Autumun --> Autumn

2019-07-05 09:51 UTC, francescobrivio commented on src/TauTriggerSFs2017.cc
> +
delete the two spaces

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +  myIDandISOScaleFactor[0] -> init_ScaleFactor("weights/idIso_SF_2018/Muon_Run2018_IdIso.root");
move this weight file to "/weights/HTT_SF_2016/Muon/Run2018/" there is no need to create a new "idIso_SF_2018" folder

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +  myIDandISOScaleFactor[1] -> init_ScaleFactor("weights/idIso_SF_2018/Electron_Run2018_IdIso.root");
move this weight file to "/weights/HTT_SF_2016/Electron/Run2018/" there is no need to create a new "idIso_SF_2018" folder

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +      TLorentzVector vGenB2; // bjet-2 tlv                     ##QUI##
remove all the "##QUI##"

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +	      bool isHardProcess = CheckBit (theBigTree.genpart_flags->at(igen), 7) ; //  7 = isHardProcess, for b coming from H  ##QUI##
remove "##QUI##"

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +	       // FRA DEBUG - find the bjets from the Higgs decay     ##QUI##
remove "##QUI##"

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +	        // FRA DEBUG - build gen b jets       ##QUI##
remove "##QUI##"

2019-07-05 09:51 UTC, francescobrivio commented on test/skimNtuple.cpp
> +	// ##QUI## --> QUI PUOI VEDERE UN ESEMPIO DI COME CALCOLARE LE EFFICIENZE CHE IN QUESTO CASO SONO SALVATE SU DEI BRANCH NUOVI CHE AVEVO AGGIUNTO
remove this comment line

2019-07-09 10:20 UTC, dzuolo commented
All requested changes implemented.

2019-07-09 10:28 UTC, merged